### ISSUE TITLE
Is this repos dead ?

### ISSUE THREAD

**Issue by newincpp** [call-a3/Sailfish-Slack#1]
I need this app ! but the repos seems dead. Is this project aborted ? do you plan to post it on openrepos ?

**Comment by call-a3** [comment]
It's not dead, but I'd call it "in hibernation"... My workload is currently very high, so I don't have a lot of time to work on this :( But it's good to know there's an interest from people other than myself for an app like this :)

Once I get it to a state where this app is actually usefull, I plan to post it on any channel available to me :) Jolla's official Harbour would be my first guess, but OpenRepos is definately also an option ;)

**Comment by newincpp** [comment]
awesome ! so i will just wait to see any news from you and see what happen... i hope to see news soon !
